const assert=require('assert'),fs=require('fs'),{Game,TYPES,ENEMIES}=require('../web/engine.js'),map=JSON.parse(fs.readFileSync(__dirname+'/../assets.json'));
const g=new Game(map);assert.equal(g.towers.length,2);assert(g.canBuild('n1',228,204).includes('경로'));assert(!g.addTower('n1',228,204).ok);assert.equal(g.credits,1500);
const a=g.addTower('n1',276,228);assert(a.ok);assert.equal(g.credits,1400);assert(g.upgrade(a.tower.id));assert.equal(g.credits,1335);assert(g.sell(a.tower.id));assert.equal(g.credits,1450);
assert(g.canBuild('htnk',276,228).includes('해금'));g.capacity=g.power;assert(g.canBuild('n1',276,228).includes('전력'));g.capacity=28;g.credits=0;assert(g.canBuild('n1',276,228).includes('크레딧'));
const loss=new Game(map);loss.towers=[];assert(loss.startWave());assert(!loss.startWave());loss.paused=true;loss.update(.05);assert.equal(loss.time,0);loss.paused=false;for(let i=0;i<3000&&loss.phase==='wave';i++)loss.update(.05);assert.equal(loss.phase,'intermission');assert.equal(loss.lives,9);loss.startWave();for(let i=0;i<5000&&loss.phase==='wave';i++)loss.update(.05);assert.equal(loss.phase,'lost');
const campaign=new Game(map),api=require('../web/engine.js'),samplePath=Array.from({length:80},(_,i)=>api.pointAt(map.path,i*api.pathLength(map.path)/80));function spend(){const spots=[];for(let y=84;y<=420;y+=24)for(let x=36;x<=732;x+=24)if(!campaign.validSpot(x,y))spots.push({x,y,score:samplePath.reduce((score,p)=>score+(Math.hypot(x-p.x,y-p.y)<140?1:0),0)+ (Math.abs(y-180)<90?4:0)});spots.sort((a,b)=>b.score-a.score);for(const t of campaign.towers){if(t.level<3&&campaign.credits>=campaign.upgradeCost(t)+400)campaign.upgrade(t.id)}for(let j=0;j<12;j++){const type=campaign.cleared>=6&&campaign.towers.filter(t=>t.type==='obli').length<3?'obli':campaign.cleared>=3?'atwr':campaign.cleared>=2?'msam':campaign.towers.length<5?'n3':'hmmv';if(campaign.credits<TYPES[type].cost)break;if(campaign.power+TYPES[type].power>campaign.capacity){if(campaign.credits<TYPES[type].cost+250)break;campaign.addPower()}const spot=spots.find(s=>!campaign.validSpot(s.x,s.y));if(!spot)break;campaign.addTower(type,spot.x,spot.y)}if(campaign.lives<=14)campaign.repair()}
const waves=[];for(let w=1;w<=12;w++){spend();assert(campaign.startWave());let ticks=0;while(campaign.phase==='wave'&&ticks++<10000)campaign.update(.05);waves.push({wave:w,phase:campaign.phase,lives:campaign.lives,credits:campaign.credits,towers:campaign.towers.length,kills:campaign.kills});if(campaign.phase==='lost')break;assert(ticks<10000)}console.log(JSON.stringify(waves,null,2));assert.equal(campaign.phase,'won');
const air=new Game(map);air.towers=[];air.addTower('n1',276,156,true);air.towers[0].cooldown=0;air.wave=4;air.phase='wave';air.queue=[{type:'rifle'}];air.spawn({type:'air'});const target=air.enemies[0];target.d=300;target.x=276;target.y=180;const hp=target.hp;air.update(.01);assert.equal(air.projectiles.length,0);air.towers=[];air.addTower('n3',276,156,true);air.towers[0].cooldown=0;air.update(.01);assert.equal(air.projectiles.length,1);
console.log('PASS: validation, spending, upgrade, refund, unlock, power, pause, leak/loss, all 12 waves winnable, air targeting');fs.writeFileSync(__dirname+'/../output/engine-validation.json',JSON.stringify({passed:true,waves},null,2));
