// SPDX-License-Identifier: GPL-3.0-or-later
'use strict';
const $=id=>document.getElementById(id),{Game,TYPES,ENEMIES}=FieldDefense;
ASSETS.obstacles.push({x:716,y:266,r:28},{x:684,y:90,r:28});
const game=new Game(ASSETS),catalog=Object.fromEntries(ASSETS.units.map(u=>[u.id,u])),images=new Map();
let selectedId=null,buildMode=null,productionTab='units',hover=null,grid=false,sound=false,audioCtx=null,lastShot=0,lastTime=0,lastUI=0,modalPaused=false,lastFocus=null,endedDismissed=false;
const canvas=$('field'),ctx=canvas.getContext('2d'),radar=$('radar').getContext('2d');
function load(src){if(images.has(src))return Promise.resolve(images.get(src));const im=new Image();images.set(src,im);return new Promise((resolve,reject)=>{im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('이미지 데이터를 불러오지 못했습니다.'));im.src=src})}
function img(src){return images.get(src)}
function faceIndex(angle,n){return((Math.round((-angle-Math.PI/2)/(Math.PI*2)*n)%n)+n)%n}
function unitSprite(id,x,y,angle=0,mode='idle',time=0,enemy=false,scale=1,layers=false){const u=catalog[id];if(!u)return;ctx.imageSmoothingEnabled=false;
 if(layers&&u.layers){for(const name of ['idle','turret']){const l=u.layers[name],im=img(l.src),i=faceIndex(name==='idle'?Math.PI:angle,32);if(im)ctx.drawImage(im,i%l.cols*l.w,Math.floor(i/l.cols)*l.h,l.w,l.h,Math.round(x-l.w*scale/2),Math.round(y-l.h*scale/2),l.w*scale,l.h*scale)}return}
 const modes=enemy&&u.enemyModes?u.enemyModes:u.modes,m=modes[mode]||modes[u.defaultMode],im=img(m.src);if(!im)return;const f=faceIndex(angle,m.facings),a=Math.floor(time*1000/m.tick)%m.length,i=f*m.length+a,s=m.size*scale;ctx.drawImage(im,i%m.cols*m.size,Math.floor(i/m.cols)*m.size,m.size,m.size,Math.round(x-s/2),Math.round(y-s/2),s,s)
}
function line(x1,y1,x2,y2,color,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}
function circle(x,y,r,color,fill=false){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(fill){ctx.fillStyle=color;ctx.fill()}else{ctx.strokeStyle=color;ctx.stroke()}}
function bracket(x,y,w,color){ctx.strokeStyle=color;ctx.lineWidth=1;for(const [sx,sy] of [[-1,-1],[1,-1],[-1,1],[1,1]]){ctx.beginPath();ctx.moveTo(x+sx*w,y+sy*(w-6));ctx.lineTo(x+sx*w,y+sy*w);ctx.lineTo(x+sx*(w-6),y+sy*w);ctx.stroke()}}
function render(){ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,768,480);ctx.imageSmoothingEnabled=false;ctx.drawImage(img(ASSETS.terrain),0,0,768,480);
 // Friendly base and supporting facilities use the same extracted artwork.
 unitSprite('pyle',684,90,0,'idle',game.time);unitSprite('nuke',716,266,0,'idle',game.time);unitSprite('hq',710,180,0,'idle',game.time);
 ctx.fillStyle='#111b0add';ctx.fillRect(680,214,60,6);ctx.fillStyle=game.lives>6?'#83c878':'#e36d49';ctx.fillRect(681,215,58*game.lives/20,4);
 ctx.font='8px "Field UI",monospace';ctx.fillStyle='#d9e3b2';ctx.fillText('사령부',696,230);
 if(grid||buildMode){ctx.fillStyle='#c9e28c60';for(let y=84;y<=420;y+=24)for(let x=36;x<=732;x+=24)if(!game.validSpot(x,y))ctx.fillRect(x-.65,y-.65,1.3,1.3)}
 // Direction chevrons stay subtle and make the route readable at all sizes.
 ctx.strokeStyle='#d4b87588';ctx.lineWidth=1.2;for(const [x,y,a] of [[22,108,0],[228,218,Math.PI/2],[360,348,0],[516,265,-Math.PI/2],[625,180,0]]){ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.beginPath();ctx.moveTo(-3,-4);ctx.lineTo(2,0);ctx.lineTo(-3,4);ctx.stroke();ctx.restore()}
 const sel=game.towers.find(t=>t.id===selectedId);if(sel&&!buildMode){const a=game.stats(sel);circle(sel.x,sel.y,a.range,'#adc97620',true);ctx.setLineDash([3,4]);circle(sel.x,sel.y,a.range,'#c6dd8575');ctx.setLineDash([])}
 const actors=[...game.towers.map(t=>({...t,friend:true})),...game.enemies].sort((a,b)=>(a.air?1000:a.y)-(b.air?1000:b.y));
 for(const a of actors){if(a.friend){const u=catalog[a.type],mode=u.group==='infantry'?(a.attack>0?(u.modes.shoot?'shoot':u.modes.throw?'throw':'stand'):'stand'):'idle';unitSprite(a.type,a.x,a.y,a.face,mode,game.time,false,1.12,u.group==='vehicles');if(a.id===selectedId)bracket(a.x,a.y,19,'#e6dc88');ctx.fillStyle='#c5cd72';for(let i=0;i<a.level;i++)ctx.fillRect(a.x-4+i*4,a.y+19,3,2);}
 else{if(a.air){ctx.fillStyle='#0006';ctx.beginPath();ctx.ellipse(a.x+5,a.y+13,12,5,0,0,Math.PI*2);ctx.fill()}unitSprite(a.sprite,a.x,a.y-(a.air?9:0),a.angle,a.type==='rifle'?'run':'idle',game.time,true,a.boss?1.45:1.1);if(a.flash>0)bracket(a.x,a.y,14,'#ffddac');const w=a.boss?38:23,y=a.y-(a.air?26:21);ctx.fillStyle='#170c0bcc';ctx.fillRect(a.x-w/2-1,y-1,w+2,4);ctx.fillStyle=a.boss?'#ff975f':'#cc5c45';ctx.fillRect(a.x-w/2,y,w*Math.max(0,a.hp/a.maxHp),2);if(a.boss){ctx.fillStyle='#f5ca85';ctx.font='7px monospace';ctx.fillText('COMMANDER',a.x-22,y-4)}}}
 for(const p of game.projectiles){const dx=p.tx-p.x,dy=p.ty-p.y,d=Math.max(1,Math.hypot(dx,dy));line(p.x-dx/d*(p.kind==='bullet'?7:5),p.y-dy/d*5,p.x,p.y,p.kind==='bullet'?'#f7e29c':p.kind==='rocket'?'#f6b569':'#e4cf87',p.kind==='bullet'?1:2);if(p.kind==='rocket'){circle(p.x-dx/d*6,p.y-dy/d*6,2,'#ee7235aa',true);circle(p.x-dx/d*11,p.y-dy/d*11,2,'#cac6a650',true)}}
 for(const f of game.effects){const q=f.age/f.duration;if(f.kind==='laser'){line(f.sx,f.sy,f.tx,f.ty,'#ff3c38aa',4*(1-q));line(f.sx,f.sy,f.tx,f.ty,'#ffc6a4',1)}else{const r=f.r*(.4+.8*q);circle(f.x,f.y,r,`rgba(213,110,41,${(1-q)*.55})`,true);circle(f.x,f.y,r*.5,`rgba(255,224,143,${1-q})`,true);for(let k=0;k<5;k++){const a=k*1.25+f.x;ctx.fillStyle=`rgba(238,178,74,${1-q})`;ctx.fillRect(f.x+Math.cos(a)*r-1,f.y+Math.sin(a)*r-1,2,2)}}}
 if(buildMode&&hover){const a=TYPES[buildMode],error=game.canBuild(buildMode,hover.x,hover.y),color=error?'#ee725b':'#c0e09b';circle(hover.x,hover.y,a.range,error?'#f8775120':'#bfd88720',true);ctx.setLineDash([3,4]);circle(hover.x,hover.y,a.range,color+'99');ctx.setLineDash([]);ctx.globalAlpha=.7;unitSprite(buildMode,hover.x,hover.y,Math.PI,catalog[buildMode].defaultMode,game.time);ctx.globalAlpha=1;bracket(hover.x,hover.y,19,color)}
 renderRadar()
}
function renderRadar(){radar.clearRect(0,0,384,200);radar.fillStyle='#0c1c10';radar.fillRect(0,0,384,200);radar.globalAlpha=.32;radar.drawImage(img(ASSETS.terrain),0,0,384,200);radar.globalAlpha=1;radar.strokeStyle='#7d995a';radar.lineWidth=2;radar.beginPath();ASSETS.path.forEach(([x,y],i)=>i?radar.lineTo(x/2,y/2.4):radar.moveTo(x/2,y/2.4));radar.stroke();for(const t of game.towers){radar.fillStyle='#aadd7b';radar.fillRect(t.x/2-2,t.y/2.4-2,4,4)}for(const e of game.enemies){radar.fillStyle='#f16b50';radar.fillRect(e.x/2-2,e.y/2.4-2,4,4)}radar.strokeStyle='#c6d99d';radar.strokeRect(349,69,14,14);radar.strokeStyle='#a7d89818';radar.beginPath();radar.moveTo(192,100);const a=game.time*.65;radar.lineTo(192+Math.cos(a)*220,100+Math.sin(a)*220);radar.stroke()}
function message(text,bad=false){$('message').textContent=text;$('message').style.color=bad?'#eda18b':'#c1ccad'}
function soundFx(kind){if(!sound||!audioCtx)return;const now=audioCtx.currentTime;if(kind==='shot'&&now-lastShot<.10)return;if(kind==='shot')lastShot=now;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.connect(g);g.connect(audioCtx.destination);o.type=kind==='shot'?'triangle':'sine';const f=kind==='shot'?130:kind==='wave'?460:710;o.frequency.setValueAtTime(f,now);o.frequency.exponentialRampToValueAtTime(kind==='shot'?38:f*.68,now+.1);g.gain.setValueAtTime(kind==='shot'?.018:.05,now);g.gain.exponentialRampToValueAtTime(.001,now+.12);o.start(now);o.stop(now+.14)}
function processEvents(){while(game.events.length){const e=game.events.shift();if(e.type==='shot')soundFx('shot');else if(e.text){message(e.text,e.type==='error'||e.type==='leak');if(e.type!=='status')$('log').textContent=e.text;if(['wave','clear','build'].includes(e.type))soundFx(e.type)}if(e.type==='clear'){buildProduction();if(game.phase!=='won')message(e.text+' · 재편성 후 다음 웨이브를 시작하세요.')}if(e.type==='end')showEnd()}}
function chooseBuild(type){const a=TYPES[type];if(!a||game.cleared<a.unlock){message(`${a?.unlock||0}차 방어 후 해금됩니다.`,true);return}if(['lost','won'].includes(game.phase))return;buildMode=type;selectedId=null;hover=null;message(a.name+' 선택 · 잔디를 눌러 배치하세요.');soundFx('click');updateUI();}
function cancelBuild(){buildMode=null;hover=null;updateUI()}
function buildProduction(){const keys=Object.keys(TYPES).filter(k=>productionTab==='defense'?['gtwr','atwr','obli'].includes(k):!['gtwr','atwr','obli'].includes(k));$('production').replaceChildren();for(const key of keys){const a=TYPES[key],locked=game.cleared<a.unlock,b=document.createElement('button');b.className='buildcard';b.dataset.unit=key;b.title=a.desc;b.setAttribute('aria-label',`${a.name} 생산 $${a.cost}${locked?' · '+a.unlock+'차 방어 후 해금':''}`);b.innerHTML=`<span class="unitart"><img src="${catalog[key].thumb}" alt=""></span><span class="caption"><span>${a.name}</span><span class="price">$${a.cost}</span></span><span class="typehint">${locked?'▣ '+a.unlock+'차 방어 후 해금':a.air?'대공 가능 · 전력 '+a.power:'지상 공격 · 전력 '+a.power}</span>`;b.onclick=()=>chooseBuild(key);$('production').append(b)}}
function updateSelection(){const t=game.towers.find(t=>t.id===selectedId),key=buildMode||(t&&t.type),a=key?(t?game.stats(t):TYPES[key]):null;$('selectedPortrait').src=catalog[key||'hq'].thumb;$('upgradeBtn').disabled=!t||t.level>=3||game.credits<game.upgradeCost(t)||['won','lost'].includes(game.phase);$('sellBtn').disabled=!t||['won','lost'].includes(game.phase);
 if(a){$('selectedTitle').textContent=a.name+(buildMode?' · 배치 준비':' · Lv.'+t.level);$('selectedDesc').textContent=a.desc;$('selectedStats').textContent=`공격 ${a.damage} / 사거리 ${a.range} / 전력 ${a.power}${a.air?' / 지상·공중':' / 지상'}`;$('upgradeBtn').textContent=t?(t.level>=3?'최대 강화 Lv.3':`강화 $${game.upgradeCost(t)}`):`배치 비용 $${a.cost}`;$('sellBtn').textContent=t?`철수 +$${Math.floor(t.spent*.7)}`:'잔디를 눌러 배치'}else{$('selectedTitle').textContent='사령부 · 전진기지';$('selectedDesc').textContent='유닛을 선택하면 사거리와 강화 정보를 봅니다.';$('selectedStats').textContent=`${game.kills} 격파 / ${game.towers.length}기 배치 / ${game.cleared}차 방어 성공`;$('upgradeBtn').textContent='유닛을 선택하세요';$('sellBtn').textContent='철수 / 70% 회수'}
 $('cancelBuild').hidden=!buildMode;$('mapHint').textContent=buildMode?TYPES[buildMode].name+' 배치 · 밝은 점이 배치 가능 위치':t?'선택한 유닛 강화 가능 · 원은 공격 사거리':'유닛 선택 → 잔디에 배치 → 웨이브 시작';}
const enemyNames={rifle:'보병',buggy:'버기',bike:'바이크',tank:'경전차',heavy:'중전차',air:'공습'};
function updateUI(){const end=['won','lost'].includes(game.phase);$('credits').textContent='$'+game.credits.toLocaleString();$('health').textContent=game.lives+' / 20';$('health').style.color=game.lives<=6?'#e88466':'#89c68c';$('powerText').textContent=game.power+' / '+game.capacity;$('powerFill').style.width=Math.min(100,game.power/game.capacity*100)+'%';$('waveTitle').textContent='WAVE '+String(game.phase==='ready'||game.phase==='intermission'?Math.min(12,game.wave+1):game.wave).padStart(2,'0')+' / 12';$('enemyCount').textContent=game.phase==='wave'?(game.enemies.length+game.queue.length)+' HOSTILES':end?'COMPLETE':'READY';$('waveBrief').textContent=game.phase==='wave'?`남은 적 ${game.enemies.length} · 추가 진입 ${game.queue.length}`:end?(game.phase==='won'?'작전 성공 · 사령부 방어 완료':'사령부 함락 · 재도전 가능'):'다음: '+game.preview().map(k=>enemyNames[k]).join(' / ');$('waveBtn').disabled=game.phase==='wave'||end||game.paused;$('waveBtn').textContent=end?(game.phase==='won'?'작전 성공':'작전 종료'):game.phase==='wave'?'● 교전 중':`▶ ${game.wave+1}차 웨이브 시작`;$('pauseBtn').textContent=game.paused?'계속하기':'일시정지';$('pauseBtn').disabled=end;$('speedBtn').textContent='속도 '+game.speed+'×';$('missionState').textContent=game.paused?'작전 일시정지':game.phase==='wave'?`${game.wave}차 교전 중 · 목표: 사령부 방어`:end?'작전 종료':'배치 대기 · 좌측에서 적 진입';$('footerStats').textContent=game.kills+' KILLS · '+game.towers.length+' UNITS';$('powerBtn').disabled=game.credits<250||end;$('repairBtn').disabled=game.credits<220||game.lives===20||end;for(const b of $('production').children){const a=TYPES[b.dataset.unit];b.classList.toggle('locked',game.cleared<a.unlock);b.classList.toggle('poor',game.credits<a.cost);b.classList.toggle('active',buildMode===b.dataset.unit);b.setAttribute('aria-pressed',String(buildMode===b.dataset.unit))}updateSelection()}
function togglePause(){if(['won','lost'].includes(game.phase))return;game.paused=!game.paused;message(game.paused?'작전 일시정지 · 계속하기로 재개하세요.':'작전을 재개합니다.');updateUI()}
function showEnd(){if(endedDismissed)return;$('announce').hidden=false;$('announceTitle').textContent=game.phase==='won'?'MISSION ACCOMPLISHED':'MISSION FAILED';$('announceText').textContent=`${game.wave}차 웨이브 · ${game.kills} 격파 · 사령부 ${game.lives}/20`;$('announceAction').textContent='새 작전 시작';$('announceAction').onclick=resetGame;$('reviewBtn').hidden=false}
function resetGame(){game.reset();selectedId=null;buildMode=null;hover=null;endedDismissed=false;$('announce').hidden=true;buildProduction();processEvents();updateUI()}
function openModal(id){lastFocus=document.activeElement;modalPaused=game.paused;game.paused=true;$(id).hidden=false;$(id).querySelector('button').focus();updateUI()}
function closeModal(id){$(id).hidden=true;game.paused=modalPaused;lastFocus?.focus();updateUI()}
function world(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*768/r.width,y:(e.clientY-r.top)*480/r.height}}
canvas.addEventListener('pointermove',e=>{const p=world(e);hover={x:Math.floor(p.x/24)*24+12,y:Math.floor(p.y/24)*24+12}});canvas.addEventListener('pointerleave',()=>{hover=null});canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.focus({preventScroll:true});if(['won','lost'].includes(game.phase))return;const p=world(e),t=game.towers.find(t=>Math.hypot(p.x-t.x,p.y-t.y)<21);if(t){selectedId=t.id;buildMode=null;updateUI();soundFx('click');return}if(buildMode){const x=Math.floor(p.x/24)*24+12,y=Math.floor(p.y/24)*24+12,r=game.addTower(buildMode,x,y);if(r.ok){selectedId=r.tower.id;buildMode=null;hover=null;processEvents()}else{message(r.error,true);soundFx('click');hover={x,y}}}else selectedId=null;updateUI()});canvas.addEventListener('contextmenu',e=>{e.preventDefault();cancelBuild()});
$('unitTab').onclick=()=>{productionTab='units';$('unitTab').classList.add('active');$('defenseTab').classList.remove('active');buildProduction();updateUI()};$('defenseTab').onclick=()=>{productionTab='defense';$('defenseTab').classList.add('active');$('unitTab').classList.remove('active');buildProduction();updateUI()};$('cancelBuild').onclick=cancelBuild;$('waveBtn').onclick=()=>{game.startWave();processEvents();updateUI()};$('pauseBtn').onclick=togglePause;$('speedBtn').onclick=()=>{game.speed=game.speed===1?2:1;updateUI()};$('gridBtn').onclick=()=>{grid=!grid;$('gridBtn').setAttribute('aria-pressed',String(grid))};$('upgradeBtn').onclick=()=>{game.upgrade(selectedId);processEvents();updateUI()};$('sellBtn').onclick=()=>{game.sell(selectedId);selectedId=null;processEvents();updateUI()};$('powerBtn').onclick=()=>{game.addPower();processEvents();updateUI()};$('repairBtn').onclick=()=>{game.repair();processEvents();updateUI()};$('helpBtn').onclick=()=>openModal('helpModal');$('atlasBtn').onclick=()=>openModal('atlasModal');for(const el of document.querySelectorAll('[data-close]'))el.onclick=()=>closeModal(el.dataset.close);$('reviewBtn').onclick=()=>{endedDismissed=true;$('announce').hidden=true};$('restartBtn').onclick=()=>{if(confirm('현재 작전을 끝내고 처음부터 다시 시작할까요?'))resetGame()};$('fullBtn').onclick=()=>{const p=document.fullscreenElement?document.exitFullscreen?.():document.documentElement.requestFullscreen?.();p?.catch(()=>message('이 브라우저에서는 전체 화면을 지원하지 않습니다.'))};$('soundBtn').onclick=async()=>{sound=!sound;if(sound){const AC=window.AudioContext||window.webkitAudioContext;if(!AC){sound=false;message('이 브라우저에서는 음향을 지원하지 않습니다.');return}audioCtx??=new AC();await audioCtx.resume();soundFx('click')}$('soundBtn').textContent='음향 '+(sound?'ON':'OFF');$('soundBtn').setAttribute('aria-pressed',String(sound))};
for(const u of ASSETS.units){const el=document.createElement('div');el.className='atlascard';el.innerHTML=`<img src="${u.thumb}" alt="${u.ko}"><b>${u.ko}</b><small>${u.name}</small><small>${TYPES[u.id]?'작전 편성 가능':'후속 확장 후보'}</small>`;if(TYPES[u.id]){const b=document.createElement('button');b.textContent='생산 선택';b.onclick=()=>{closeModal('atlasModal');chooseBuild(u.id)};el.append(b)}$('atlasGrid').append(el)}
document.addEventListener('keydown',e=>{const modal=['helpModal','atlasModal'].find(id=>!$(id).hidden);if(modal){if(e.key==='Escape')closeModal(modal);if(e.key==='Tab'){const focusable=[...$(modal).querySelectorAll('button')];if(e.shiftKey&&document.activeElement===focusable[0]){e.preventDefault();focusable.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===focusable.at(-1)){e.preventDefault();focusable[0].focus()}}return}if(e.target.matches('button,input,select'))return;if(e.code==='Space'){e.preventDefault();if(['ready','intermission'].includes(game.phase)&&!game.paused)game.startWave();else togglePause();processEvents();updateUI()}if(e.key==='Escape')cancelBuild();if(e.key.toLowerCase()==='g')$('gridBtn').click()});
window.pauseGame=()=>{if(!['won','lost'].includes(game.phase)){game.paused=true;updateUI()}};document.addEventListener('visibilitychange',()=>{if(document.hidden)window.pauseGame()});
function loop(now){const dt=lastTime?Math.min(.05,(now-lastTime)/1000):0;lastTime=now;game.update(dt);processEvents();render();if(now-lastUI>120){updateUI();lastUI=now}requestAnimationFrame(loop)}
const sources=new Set([ASSETS.terrain]);for(const u of ASSETS.units){for(const m of Object.values(u.modes))sources.add(m.src);if(u.enemyModes)for(const m of Object.values(u.enemyModes))sources.add(m.src);if(u.layers)for(const m of Object.values(u.layers))sources.add(m.src)}
Promise.all([...sources].map(load)).then(()=>{buildProduction();processEvents();updateUI();$('loading').hidden=true;requestAnimationFrame(loop);window.__fieldReady=true}).catch(err=>{$('loading').textContent=err.message+' 새로고침해 주세요.'});
// Read-only state access for automated verification; gameplay mutations stay in Game methods.
window.FieldDefenseDebug={game,render,updateUI,chooseBuild};
